#!/usr/bin/env bash
# Run the UE-scaling sweep for each Walker-Star constellation size (3/6/12/24)
# and emit one CSV per constellation in results/.
#
# Usage: scratch/run-constellation-sweep.sh [sim_time_seconds] [seed] [packet_interval_s] [jitter_ms]
#
# Requires the TLE files generated by scratch/gen-walker-tles.py.

set -euo pipefail

SIM_TIME="${1:-60}"
SEED="${2:-21}"
PACKET_INTERVAL="${3:-10}"
JITTER_MS="${4:-1000}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# Make sure the TLE files exist; (re)generate if any are missing.
need_gen=0
for N in 3 6 12 24; do
  if [[ ! -f "scratch/tle-data/walker-${N}sat.tle" ]]; then
    need_gen=1
  fi
done
if [[ $need_gen -eq 1 ]]; then
  echo "==> Generating Walker-Star TLE files..."
  python3 scratch/gen-walker-tles.py
fi

# Build once up front so wall time isn't dominated by the linker.
./ns3 build > /dev/null

for N in 3 6 12 24; do
  LABEL="walker-${N}sat"
  TLE="scratch/tle-data/walker-${N}sat.tle"
  echo
  echo "############# Constellation: ${N} satellites (${LABEL}) #############"
  scratch/run-ue-scaling.sh "$SIM_TIME" "$SEED" "$PACKET_INTERVAL" "$JITTER_MS" \
                            "$LABEL" "$TLE" "$N"
done

echo
echo "All constellation sweeps complete. CSVs:"
ls -1 results/ue-scaling-walker-*.csv | tail -4
echo
echo "Plot the comparison with:"
echo "  python3 scratch/plot-constellation-compare.py results/ue-scaling-walker-3sat-*.csv \\"
echo "                                               results/ue-scaling-walker-6sat-*.csv \\"
echo "                                               results/ue-scaling-walker-12sat-*.csv \\"
echo "                                               results/ue-scaling-walker-24sat-*.csv"
